### ISSUE TITLE
Hi bro i am facing this below errors while running the "flask run" please help me to resolve it bro..

### ISSUE THREAD

**Issue by Hemanath78** [abhayshah0305/RiskAssess#1]
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\Scripts\flask.exe\__main__.py", line 4, in <module>
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\__init__.py", line 19, in <module>
    from . import json
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\json\__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\site-packages\itsdangerous\__init__.py)

**Comment by krishnanand654** [comment]
The "ImportError: cannot import name 'json' from 'itsdangerous'" error occurs due to incompatibility between Flask and itsdangerous package

. The json module has been removed from the itsdangerous package, which causes this error

. To fix this error, you can upgrade your version of Flask to version 2 or higher, which uses the TimedJSONWebSignatureSerializer method from itsdangerous instead of json

. Alternatively, you can downgrade your version of itsdangerous to version 2.0.1
``` 
pip uninstall itsdangerous
pip install itsdangerous==2.0.1
```

**Comment by pratyush2611s** [comment]
brother im getting this error everytime i run this code using flask run command

C:\Users\praty\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:376: InconsistentVersionWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.24.1 when using version 1.4.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\praty\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\praty\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\praty\AppData\Local\Programs\Python\Python310\Scripts\flask.exe\__main__.py", line 7, in <module>
  File "C:\Users\praty\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\cli.py", line 1105, in main
    cli.main()
  File "C:\Users\praty\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "C:\Users\praty\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\praty\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\praty\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\praty\AppData\Local\Programs\Python\Python310\lib\site-packages\click\decorators.py", line 92, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "C:\Users\praty\AppData\Local\Programs\Python\Python310\lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\praty\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\cli.py", line 953, in run_command
    raise e from None
  File "C:\Users\praty\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\cli.py", line 937, in run_command
    app: WSGIApplication = info.load_app()
  File "C:\Users\praty\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\cli.py", line 339, in load_app
    app = locate_app(import_name, None, raise_if_not_found=False)
  File "C:\Users\praty\AppData\Local\Programs\Python\Python310\lib\site-packages\flask\cli.py", line 245, in locate_app
    __import__(module_name)
  File "C:\Users\praty\Work\RiskAssess-master\RiskAssess-master\app.py", line 17, in <module>
    classifier = pickle.load(open(filename, 'rb'))
  File "sklearn\\tree\\_tree.pyx", line 865, in sklearn.tree._tree.Tree.__setstate__
  File "sklearn\\tree\\_tree.pyx", line 1571, in sklearn.tree._tree._check_node_ndarray
ValueError: node array from the pickle has an incompatible dtype:
- expected: {'names': ['left_child', 'right_child', 'feature', 'threshold', 'impurity', 'n_node_samples', 'weighted_n_node_samples', 'missing_go_to_left'], 'formats': ['<i8', '<i8', '<i8', '<f8', '<f8', '<i8', '<f8', 'u1'], 'offsets': [0, 8, 16, 24, 32, 40, 48, 56], 'itemsize': 64}
- got     : [('left_child', '<i8'), ('right_child', '<i8'), ('feature', '<i8'), ('threshold', '<f8'), ('impurity', '<f8'), ('n_node_samples', '<i8'), ('weighted_n_node_samples', '<f8')]


can you help please
